### ISSUE TITLE
Metadata Consistency

### ISSUE THREAD

**Issue by jmrichardson** [Norconex/collector-filesystem#16]
Hi, it appears that some document types do not have what I thought would be available for all documents.  For example, .txt files do not have the following metadata:

Date created
Author/owner
Word count

These are included in word docs for example.  Is there a way to add these to all files or is there some limitation?

Thanks

**Comment by essiembre** [comment]
Fields starting with ``collector.`` or ``document.`` are set up by the Collector and Importer respectively and should be fairly common to all docs.  ``collector.attribute.*`` should contain all file attributes obtained by querying the filesystem you are using (info that can be obtained without opening the document).  The rest of the fields obtained are dependant on what each document has and varies for each document and content types.  If you do not see a field, it is normally because it does not exist or was not available.  For instance, "author" is often a property field stored within PDF or MS Word document, but not in Txt files.

Sometimes the information is found under a different name.  Using the ``DebugTagger`` to print extracted fields (as a post-parse handler) can be quite helpful to figure that out.  You can use the ``RenameTagger`` to normalize your field names.

You can look at a few different "taggers" from importer module to extract the information you are looking for if it is part of the document content.   You can also use the ``ConstantTagger`` to provide a default value for a field if none is found.

Additional suggestions for those you list:

**Date created**
If that information could not be extracted from the file, you may want to consider using ``collector.lastmodified`` instead.  If not present, you can fall back to using a [CurrentDateTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/CurrentDateTagger.html).  It will store the current date which is not the same at first, but after a while, the current date could closely match the date of new documents appearing on your filesystem.

**Author/owner**
If that field does not exist for a document, you may consider falling back to a relevant portion of the directory path, if applicable (e.g. if your directory structure is divided by department, the department name could be the author/owner).

**Word count**
If not provided by the file, you can obtain it with [TextStatisticsTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/TextStatisticsTagger.html).  [DocumentLengthTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/DocumentLengthTagger.html) may also be relevant to you.

**Comment by jmrichardson** [comment]
Thank you.  That is very helpful.
