### ISSUE TITLE
Overriding the IDocumentParser halfly encodes the output xml

### ISSUE THREAD

**Issue by jayjamba** [Norconex/collector-filesystem#25]
Hi,
I have uploaded my custom parser which I am using for plain text files to parse it, however after parsing I noticed that it encodes the output document half way, as in, if it finds some element like `<html>` it will encode like `&lt;html>` and NOT LIKE `&lt;html&gt;`.
Not sure if I am missing anything. I have attached config xml, custom document parser and the output file for your reference.
[files.zip](https://github.com/Norconex/collector-filesystem/files/1743771/files.zip)

**Comment by essiembre** [comment]
Because you are using the XML committer, your content needs to be XML-escaped.  The implementation of the XML writer happens to encode the minimum required (as per https://www.w3.org/TR/xml/#syntax).  That is why you only have the ``&`` and ``<`` characters encoded.

Any compliant XML parser should decode your content properly. Are you experiencing parsing issues?
