### ISSUE TITLE
DFS (distributed File System) Index

### ISSUE THREAD

**Issue by angelo337** [Norconex/collector-filesystem#34]
hi there
I am trying to index a DFS on MS Windows, however I am not able to index that system by name, do you have any idea? or test that I shuld run?
thanks a lot
angelo

**Comment by essiembre** [comment]
You are not giving much details. :-)  Do you get any errors?  Have you tried mounting it as a drive and crawling that drive as if it was a local filesystem?  Otherwise, have you tried with the JCIFS library installed (as described somewhere on [this](https://www.norconex.com/collectors/collector-filesystem/getting-started) page?

**Comment by angelo337** [comment]
Hi there
I manage to figure out why that is failing, you can not crawl a DFS (MS) from a linux machine or a Windows Home.
thanks a lot for your help
