### ISSUE TITLE
It is crawling the older paths, even if its modified to newer path.

### ISSUE THREAD

**Issue by jayjamba** [Norconex/collector-filesystem#41]
Hi,
I just set up filesystem collector in my machine and I crawled one path under it. It crawled successfully and generated xml of all files under that path. Now lets say I am modifying the path under variable file, though it crawled all the files under the new path but it also crawled the older path and rejected the files of that path since it were not modified. But my question is why it actually went to crawl the older path ?

**Comment by essiembre** [comment]
This happens because the crawler performs incremental crawls and picks up changes from one run to the other.  To know if the previously crawled files have changed or have been deleted, they need to be crawled again.  If you do not want to have these "orphans" reprocessed, set the orphan strategy to IGNORE or DELETE in your crawler config. E.g.:
```xml
<orphansStrategy>IGNORE</orphansStrategy>
```

**Comment by jayjamba** [comment]
This worked. Thanks !

**Comment by essiembre** [comment]
Thanks for confirming.
