### ISSUE TITLE
How to skip subdirectories in file system crawling

### ISSUE THREAD

**Issue by Czaniolo** [Norconex/collector-filesystem#69]
Hi Pascal

I would like to prevent some subdirectories from being crawled. Is there any way to do this? I tried to use as below, but it scans the subdirectory and rejects the crawled files, because of the filter. However, I would like the subdirectory not to be crawled at all.

```xml
  <crawlerDefaults>
    <documentFilters>
      <filter
        class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="exclude">
          .*&#47;AlaraHomePage/.*
      </filter>
      <filter class="com.norconex.collector.core.filter.impl.ExtensionReferenceFilter" onMatch="include">
        doc,docx,eml,msg,mbox,ods,odt,odp,pdf,pps,ppt,pptx,pub,rar,rtf,txt,vsd,vsdx,wps,xls,xlsx,xps,zip
      </filter>
    </documentFilters>
  </crawlerDefaults>
```
![image](https://github.com/Norconex/collector-filesystem/assets/20020291/d974de61-0f61-4df7-b924-0411f1f4c614)

Thank You!

**Comment by ohtwadi** [comment]
A  [ReferenceFilter](https://opensource.norconex.com/crawlers/filesystem/configuration#tbl-referenceFilters) makes more sense here. Specifically,  [RegexReferenceFilter](https://opensource.norconex.com/crawlers/core/v1/apidocs/com/norconex/collector/core/filter/impl/RegexReferenceFilter.html) might do the trick.

**Comment by Czaniolo** [comment]
Hi,

Thank you for your reply!

I tried this, but the result was the same. Maybe I don't know how to use it...

```xml
      <importer>
        <documentParserFactory>
          <filter
            class="com.norconex.collector.core.filter.impl.ReferenceFilter" onMatch="exclude">
              .*&#47;Contrato 6Design/.*
          </filter>
```

**Comment by essiembre** [comment]
I would follow @ohtwadi's advice and use a [RegexReferenceFilter](https://opensource.norconex.com/crawlers/core/v1/apidocs/com/norconex/collector/core/filter/impl/RegexReferenceFilter.html) (you have it as `ReferenceFilter`).

Also, that filter goes higher up in your config.  See where it goes [here](https://opensource.norconex.com/crawlers/filesystem/configuration#cfg-referenceFilters).

**Comment by Czaniolo** [comment]
Hi, Pascal

Sorry. I posted it wrong (the first 2 lines don't exist and that snippet is in <documentFilters>). But, using RegexReferenceFilter is what I tried, initially (see, please, the beginning of the post).

**Comment by Czaniolo** [comment]
Maybe I am not expressing myself correctly. The filter works, as it is at the beginning of the post, and the files in that directory are not saved. The problem is that the crawler reads all the files in that directory, and then discards them. What I would like is for it to skip the directory without reading the files, for the sake of efficiency.

**Comment by ohtwadi** [comment]
Your initial post is using the `RegexReferenceFilter` as a [DocumentFilter](https://opensource.norconex.com/crawlers/filesystem/configuration#cfg-documentFilters), which will "Filter a document after the document content is fetched, downloaded, or otherwise read or acquired." ([source](https://opensource.norconex.com/crawlers/core/v1/apidocs/com/norconex/collector/core/filter/IDocumentFilter.html)). It's working as documented.

We are proposing using the `RegexReferenceFilter` as a [ReferenceFilter](https://opensource.norconex.com/crawlers/filesystem/configuration#cfg-referenceFilters), which will "Filter a document based on its reference, before its properties or content gets read or otherwise acquired." ([source](https://opensource.norconex.com/crawlers/core/v1/apidocs/com/norconex/collector/core/filter/IReferenceFilter.html))


```xml
<crawlerDefaults>
    <referenceFilters>
      <filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="exclude">
          ...
      </filter>
    </referenceFilters>
</crawlerDefaults>
```

**Comment by Czaniolo** [comment]
Hi, @ohtwadi

Really, it was a simple conceptual issue. It worked as expected, obviously.

Thanks for the clarification.

Best Regards
