### ISSUE TITLE
How to extract embedded files from .rar type archives

### ISSUE THREAD

**Issue by Czaniolo** [Norconex/collector-filesystem#71]
Hi

I tried to use inside the Importer section (with any file compressed with WinRar):

```
<documentParserFactory class="com.norconex.importer.parser.GenericDocumentParserFactory" >
    <embedded>
      <splitContentTypes>application/(x-)?rar(-compressed)?</splitContentTypes>
    </embedded>
</documentParserFactory>
```

and using: 
 
application/vnd.rar
application/octet-stream

However, the files are not extracted. The rar file is not encrypted or corrupted.

I would like to know if I am doing something wrong or if there is another solution.

Thanks!

**Comment by ohtwadi** [comment]
The Importer uses Apache Tika, which does support rar files. Are you having trouble with this one file or is this issue occurring on all rar files?

**Comment by Czaniolo** [comment]
Sorry for the delay...

In all the files tested (6 files), with different types of content, the 3 output files (.cntnt, .meta and .ref) are generated, but the file that should contain the content of the embedded file (.cntnt) does not contain any data (blank).

**Comment by ohtwadi** [comment]
Could you please provide a sample rar file we could test with?

**Comment by Czaniolo** [comment]
[norconextesterar.zip](https://github.com/Norconex/collector-filesystem/files/12386874/norconextesterar.zip)

The 2 RAR files are inside the zip file, because rar files are not allowed here...

**Comment by ohtwadi** [comment]
This is happening as Apache Tika does not support extracting RAR5 files. 

Here is one idea to move forward. Since the 7zip application extracts RAR5 files, we can use it to our advantage.

 If you are comfortable with coding, you can build a [custom Parser](https://opensource.norconex.com/importer/v3/apidocs/com/norconex/importer/parser/IDocumentParser.html) which 
i) leverages 7zip to extract the archive files. 
7zip is available on [Maven Central](https://mvnrepository.com/artifact/com.github.hazendaz.7zip/7zip/23.00).
Alternatively, install the 7zip application manually and run it in a CMD
The following extracts all `rar` files from the current directory into a `./oputput` directory.  `"C:\Program Files\7-Zip\7z.exe" e *.rar -o./output`. 
ii) sends those off to the Importer and have it do the extraction. See the Java Integration section of [Getting Started guide](https://opensource.norconex.com/importer/v2/getting-started).

You can then use this as a [ExternalParser](https://opensource.norconex.com/importer/v3/apidocs/com/norconex/importer/parser/impl/ExternalParser.html).

I am also looking at potentially using the [ExternalTransformer](https://opensource.norconex.com/importer/v3/apidocs/com/norconex/importer/handler/transformer/impl/ExternalTransformer.html) but need some time to investigate.

**Comment by ohtwadi** [comment]
Here is another option. 

You can run 2 crawlers ran separately. The first crawls everything normally except for RAR files, which are extracted in location X and otherwise rejected.  The second will crawl the extracted files in location X.

See attached zip for configs.
[rar-configs.zip](https://github.com/Norconex/collector-filesystem/files/12560406/rar-configs.zip)

**Comment by Czaniolo** [comment]
Sorry for the delay in replying!

The solution above worked. As it's a study project, there's no problem with running the crawler twice. If, eventually, this project is applied to a real situation, I'll check how to develop a custom parser to avoid running the crawler twice.

Thank you very much!
